// packages/design-system/registry/platforms/angular/checkbox.component.ts
import { Component, Input, Output, EventEmitter, forwardRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

// Checkbox variants using Tailwind classes
const checkboxVariants = {
  default: 'border-input hover:border-primary/50 focus:ring-primary',
  destructive: 'border-destructive hover:border-destructive/70 checked:bg-destructive checked:border-destructive focus:ring-destructive',
  success: 'border-green-500 hover:border-green-600 checked:bg-green-500 checked:border-green-500 focus:ring-green-500'
};

const sizeVariants = {
  sm: 'h-4 w-4',
  md: 'h-5 w-5',
  lg: 'h-6 w-6'
};

const labelSizeVariants = {
  sm: 'text-sm',
  md: 'text-base',
  lg: 'text-lg'
};

type CheckboxVariant = keyof typeof checkboxVariants;
type CheckboxSize = keyof typeof sizeVariants;

let checkboxIdCounter = 0;

@Component({
  selector: 'app-checkbox',
  standalone: true,
  imports: [CommonModule],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => CheckboxComponent),
      multi: true
    }
  ],
  template: `
    <div class="inline-flex items-center">
      <input
        [id]="inputId"
        type="checkbox"
        [class]="checkboxClasses"
        [checked]="checked"
        [disabled]="disabled"
        [required]="required"
        [attr.aria-label]="ariaLabel"
        [attr.aria-describedby]="ariaDescribedby"
        [attr.aria-invalid]="ariaInvalid"
        (change)="handleChange($event)"
      />
      <label
        *ngIf="label"
        [for]="inputId"
        [class]="labelClasses"
      >
        {{ label }}
      </label>
    </div>
  `,
  styles: [`
    input[type="checkbox"] {
      appearance: none;
      position: relative;
      cursor: pointer;
    }
    
    input[type="checkbox"]:checked::before {
      content: "✓";
      position: absolute;
      inset: 0;
      display: flex;
      align-items: center;
      justify-content: center;
      color: white;
      font-weight: bold;
    }
    
    input[type="checkbox"]:checked.h-4::before {
      font-size: 0.75rem;
    }
    
    input[type="checkbox"]:checked.h-5::before {
      font-size: 0.875rem;
    }
    
    input[type="checkbox"]:checked.h-6::before {
      font-size: 1rem;
    }
  `]
})
export class CheckboxComponent implements ControlValueAccessor {
  @Input() label = '';
  @Input() variant: CheckboxVariant = 'default';
  @Input() size: CheckboxSize = 'md';
  @Input() disabled = false;
  @Input() required = false;
  @Input() ariaLabel = '';
  @Input() ariaDescribedby = '';
  @Input() ariaInvalid = false;
  @Input() class = '';
  @Input() labelClass = '';

  @Output() checkedChange = new EventEmitter<boolean>();

  checked = false;
  inputId = `checkbox-${++checkboxIdCounter}`;

  private onChange: (value: boolean) => void = () => {};
  private onTouched: () => void = () => {};

  get checkboxClasses(): string {
    const baseClasses = 'peer rounded border-2 transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 checked:bg-primary checked:border-primary';
    const variantClass = checkboxVariants[this.variant];
    const sizeClass = sizeVariants[this.size];
    
    return `${baseClasses} ${variantClass} ${sizeClass} ${this.class}`.trim();
  }

  get labelClasses(): string {
    const baseClasses = 'ml-2 select-none cursor-pointer peer-disabled:cursor-not-allowed peer-disabled:opacity-50';
    const sizeClass = labelSizeVariants[this.size];
    
    return `${baseClasses} ${sizeClass} ${this.labelClass}`.trim();
  }

  handleChange(event: Event): void {
    const target = event.target as HTMLInputElement;
    this.checked = target.checked;
    this.onChange(this.checked);
    this.onTouched();
    this.checkedChange.emit(this.checked);
  }

  // ControlValueAccessor implementation
  writeValue(value: boolean): void {
    this.checked = value;
  }

  registerOnChange(fn: (value: boolean) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this.disabled = isDisabled;
  }
}

// packages/design-system/registry/platforms/svelte/Checkbox.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import { cva, type VariantProps } from 'class-variance-authority';
  import { cn } from '../../lib/utils';

  // Generate unique ID
  let idCounter = 0;
  const generateId = () => `checkbox-${++idCounter}`;

  // Checkbox variants
  const checkboxVariants = cva(
    [
      'peer appearance-none rounded border-2 transition-all duration-200',
      'focus:outline-none focus:ring-2 focus:ring-offset-2',
      'disabled:cursor-not-allowed disabled:opacity-50',
      'checked:bg-primary checked:border-primary',
      'checked:before:content-[""] checked:before:absolute checked:before:inset-0',
      'checked:before:flex checked:before:items-center checked:before:justify-center',
      'checked:before:text-primary-foreground',
      'relative cursor-pointer'
    ],
    {
      variants: {
        size: {
          sm: 'h-4 w-4 checked:before:text-xs',
          md: 'h-5 w-5 checked:before:text-sm',
          lg: 'h-6 w-6 checked:before:text-base'
        },
        variant: {
          default: [
            'border-input hover:border-primary/50',
            'focus:ring-primary'
          ],
          destructive: [
            'border-destructive hover:border-destructive/70',
            'checked:bg-destructive checked:border-destructive',
            'focus:ring-destructive'
          ],
          success: [
            'border-green-500 hover:border-green-600',
            'checked:bg-green-500 checked:border-green-500',
            'focus:ring-green-500'
          ]
        }
      },
      defaultVariants: {
        size: 'md',
        variant: 'default'
      }
    }
  );

  const labelVariants = cva(
    [
      'ml-2 select-none cursor-pointer',
      'peer-disabled:cursor-not-allowed peer-disabled:opacity-50'
    ],
    {
      variants: {
        size: {
          sm: 'text-sm',
          md: 'text-base',
          lg: 'text-lg'
        }
      },
      defaultVariants: {
        size: 'md'
      }
    }
  );

  type CheckboxVariant = VariantProps<typeof checkboxVariants>['variant'];
  type CheckboxSize = VariantProps<typeof checkboxVariants>['size'];

  // Props
  export let checked = false;
  export let label = '';
  export let variant: CheckboxVariant = 'default';
  export let size: CheckboxSize = 'md';
  export let disabled = false;
  export let required = false;
  export let ariaLabel = '';
  export let ariaDescribedby = '';
  export let ariaInvalid = false;
  export let className = '';
  export let labelClass = '';

  // Event dispatcher
  const dispatch = createEventDispatcher();

  // Computed
  const id = generateId();
  
  $: checkboxClasses = cn(
    checkboxVariants({ size, variant }),
    className
  );

  $: labelClasses = cn(
    labelVariants({ size }),
    labelClass
  );

  // Methods
  function handleChange(event: Event) {
    const target = event.target as HTMLInputElement;
    checked = target.checked;
    dispatch('change', checked);
  }
</script>

<div class="inline-flex items-center">
  <input
    {id}
    type="checkbox"
    class={checkboxClasses}
    bind:checked
    {disabled}
    {required}
    aria-label={ariaLabel}
    aria-describedby={ariaDescribedby}
    aria-invalid={ariaInvalid}
    on:change={handleChange}
  />
  {#if label || $$slots.default}
    <label for={id} class={labelClasses}>
      <slot>{label}</slot>
    </label>
  {/if}
</div>

<style>
  /* Checkmark icon using CSS */
  input[type="checkbox"]:checked::before {
    content: "✓";
  }
</style>
