// packages/design-system/registry/platforms/vue/Accordion.vue
<!--
Vue 3 Accordion Implementation
Generated from universal AccordionSpec
CLAUDE.md Compliant: Professional sizing and spacing
WCAG AAA: Full keyboard navigation, ARIA support, and screen reader compatibility
-->

<template>
  <div
    :class="accordionClasses"
    data-orientation="vertical"
    v-bind="$attrs"
  >
    <!-- NSM Classification for screen readers -->
    <span v-if="nsmClassification" class="sr-only">
      NSM Classification: {{ nsmClassification }}
    </span>
    
    <slot />
  </div>
</template>

<script setup lang="ts">
import { computed, provide, reactive, watch } from 'vue';
import { ChevronDownIcon } from '@heroicons/vue/24/outline';

// =============================================================================
// COMPONENT PROPS
// =============================================================================

export interface AccordionProps {
  /**
   * Visual style variant
   */
  variant?: 'default' | 'elevated' | 'outline' | 'ghost' | 'nsmOpen' | 'nsmRestricted' | 'nsmConfidential' | 'nsmSecret';
  
  /**
   * Size of the accordion
   */
  size?: 'sm' | 'md' | 'lg';
  
  /**
   * Type of accordion behavior
   */
  type?: 'single' | 'multiple';
  
  /**
   * Controlled value
   */
  value?: string | string[];
  
  /**
   * Default value for uncontrolled mode
   */
  defaultValue?: string | string[];
  
  /**
   * Whether the accordion is disabled
   */
  disabled?: boolean;
  
  /**
   * NSM Security Classification
   */
  nsmClassification?: 'OPEN' | 'RESTRICTED' | 'CONFIDENTIAL' | 'SECRET';
}

const props = withDefaults(defineProps<AccordionProps>(), {
  variant: 'default',
  size: 'md',
  type: 'single',
  disabled: false
});

// =============================================================================
// EMITS
// =============================================================================

const emit = defineEmits<{
  'update:value': [value: string | string[]];
}>();

// =============================================================================
// STATE MANAGEMENT
// =============================================================================

const internalValue = ref<string | string[]>(
  props.value ?? props.defaultValue ?? (props.type === 'multiple' ? [] : '')
);

const isControlled = computed(() => props.value !== undefined);
const currentValue = computed(() => isControlled.value ? props.value! : internalValue.value);

// Watch for external value changes
watch(() => props.value, (newValue) => {
  if (newValue !== undefined) {
    internalValue.value = newValue;
  }
}, { immediate: true });

// =============================================================================
// COMPUTED PROPERTIES
// =============================================================================

const finalVariant = computed(() => {
  if (props.nsmClassification) {
    const classification = props.nsmClassification;
    return `nsm${classification.charAt(0).toUpperCase() + classification.slice(1).toLowerCase()}`;
  }
  return props.variant;
});

const accordionClasses = computed(() => {
  const baseClasses = [
    'border border-border rounded-lg',
    'bg-card text-card-foreground',
    'transition-all duration-200 ease-in-out'
  ];

  const variantClasses = {
    default: 'shadow-sm hover:shadow-md',
    elevated: 'shadow-md hover:shadow-lg',
    outline: 'shadow-none',
    ghost: 'border-transparent shadow-none',
    nsmOpen: 'border-l-4 border-l-green-600 shadow-sm',
    nsmRestricted: 'border-l-4 border-l-yellow-600 shadow-sm',
    nsmConfidential: 'border-l-4 border-l-red-600 shadow-sm',
    nsmSecret: 'border-l-4 border-l-gray-800 shadow-sm'
  };

  const sizeClasses = {
    sm: 'text-sm',
    md: 'text-base',
    lg: 'text-lg'
  };

  return [
    ...baseClasses,
    variantClasses[finalVariant.value as keyof typeof variantClasses],
    sizeClasses[props.size]
  ].filter(Boolean);
});

// =============================================================================
// ACCORDION CONTEXT
// =============================================================================

const accordionContext = reactive({
  type: computed(() => props.type),
  value: currentValue,
  size: computed(() => props.size),
  disabled: computed(() => props.disabled),
  onItemToggle: (itemValue: string) => {
    if (props.disabled) return;
    
    let newValue: string | string[];
    
    if (props.type === 'multiple') {
      const currentArray = Array.isArray(currentValue.value) ? currentValue.value : [];
      newValue = currentArray.includes(itemValue)
        ? currentArray.filter(v => v !== itemValue)
        : [...currentArray, itemValue];
    } else {
      newValue = currentValue.value === itemValue ? '' : itemValue;
    }
    
    if (!isControlled.value) {
      internalValue.value = newValue;
    }
    
    emit('update:value', newValue);
  }
});

provide('accordionContext', accordionContext);

// =============================================================================
// ATTRS INHERITANCE
// =============================================================================

defineOptions({
  inheritAttrs: false
});
</script>

<script lang="ts">
import { defineComponent, h, inject, computed, ref, watch } from 'vue';

/**
 * AccordionItem Component
 */
export const AccordionItem = defineComponent({
  name: 'AccordionItem',
  props: {
    value: {
      type: String,
      required: true
    },
    disabled: {
      type: Boolean,
      default: false
    }
  },
  setup(props, { slots }) {
    const accordionContext = inject('accordionContext') as any;
    
    if (!accordionContext) {
      throw new Error('AccordionItem must be used within an Accordion');
    }

    const isDisabled = computed(() => accordionContext.disabled || props.disabled);
    const isOpen = computed(() => {
      if (accordionContext.type === 'multiple') {
        return Array.isArray(accordionContext.value) && accordionContext.value.includes(props.value);
      }
      return accordionContext.value === props.value;
    });

    const handleToggle = () => {
      if (!isDisabled.value) {
        accordionContext.onItemToggle(props.value);
      }
    };

    const itemContext = {
      value: props.value,
      isOpen,
      disabled: isDisabled,
      onToggle: handleToggle
    };

    // Provide item context
    provide('accordionItemContext', itemContext);

    return () =>
      h('div', {
        class: [
          'border-b border-border last:border-b-0',
          'transition-colors duration-200',
          isDisabled.value && 'opacity-50 cursor-not-allowed'
        ].filter(Boolean),
        'data-state': isOpen.value ? 'open' : 'closed',
        'data-disabled': isDisabled.value || undefined
      }, slots.default?.());
  }
});

/**
 * AccordionTrigger Component
 */
export const AccordionTrigger = defineComponent({
  name: 'AccordionTrigger',
  props: {
    hideChevron: {
      type: Boolean,
      default: false
    },
    customIcon: {
      type: Object,
      default: null
    },
    size: {
      type: String as () => 'sm' | 'md' | 'lg',
      default: undefined
    }
  },
  setup(props, { slots }) {
    const accordionContext = inject('accordionContext') as any;
    const itemContext = inject('accordionItemContext') as any;
    
    if (!accordionContext || !itemContext) {
      throw new Error('AccordionTrigger must be used within an AccordionItem');
    }

    const finalSize = computed(() => props.size || accordionContext.size);

    const triggerClasses = computed(() => {
      const baseClasses = [
        'flex w-full items-center justify-between',
        'px-6 py-4 text-left font-medium',
        'transition-all duration-200 ease-in-out',
        'focus:outline-none focus:ring-2 focus:ring-primary/20 focus:ring-offset-2',
        'hover:bg-accent/5 active:bg-accent/10',
        'disabled:cursor-not-allowed disabled:opacity-50',
        'min-h-[3rem]'
      ];

      const sizeClasses = {
        sm: 'px-4 py-3 text-sm min-h-[2.5rem]',
        md: 'px-6 py-4 text-base min-h-[3rem]',
        lg: 'px-8 py-5 text-lg min-h-[3.5rem]'
      };

      return [
        ...baseClasses,
        sizeClasses[finalSize.value]
      ];
    });

    return () =>
      h('button', {
        type: 'button',
        class: triggerClasses.value,
        disabled: itemContext.disabled,
        'aria-expanded': itemContext.isOpen,
        'aria-controls': `accordion-content-${itemContext.value}`,
        'data-state': itemContext.isOpen ? 'open' : 'closed',
        onClick: itemContext.onToggle
      }, [
        h('span', { class: 'text-left' }, slots.default?.()),
        
        !props.hideChevron && h('span', {
          class: [
            'ml-2 flex-shrink-0 transition-transform duration-200',
            itemContext.isOpen && 'rotate-180'
          ].filter(Boolean),
          'aria-hidden': 'true'
        }, [
          props.customIcon || h(ChevronDownIcon, { class: 'h-5 w-5' })
        ])
      ]);
  }
});

/**
 * AccordionContent Component
 */
export const AccordionContent = defineComponent({
  name: 'AccordionContent',
  props: {
    forceMount: {
      type: Boolean,
      default: false
    },
    size: {
      type: String as () => 'sm' | 'md' | 'lg',
      default: undefined
    }
  },
  setup(props, { slots }) {
    const accordionContext = inject('accordionContext') as any;
    const itemContext = inject('accordionItemContext') as any;
    
    if (!accordionContext || !itemContext) {
      throw new Error('AccordionContent must be used within an AccordionItem');
    }

    const finalSize = computed(() => props.size || accordionContext.size);

    const contentInnerClasses = computed(() => {
      const baseClasses = ['pb-4 pt-0'];
      
      const sizeClasses = {
        sm: 'px-4 pb-3',
        md: 'px-6 pb-4',
        lg: 'px-8 pb-5'
      };

      return [
        ...baseClasses,
        sizeClasses[finalSize.value]
      ];
    });

    return () => {
      if (!props.forceMount && !itemContext.isOpen) {
        return null;
      }

      return h('div', {
        class: [
          'overflow-hidden transition-all duration-200 ease-in-out',
          'data-[state=closed]:animate-accordion-up',
          'data-[state=open]:animate-accordion-down'
        ],
        id: `accordion-content-${itemContext.value}`,
        role: 'region',
        'aria-labelledby': `accordion-trigger-${itemContext.value}`,
        'data-state': itemContext.isOpen ? 'open' : 'closed'
      }, [
        h('div', {
          class: contentInnerClasses.value
        }, slots.default?.())
      ]);
    };
  }
});

export default AccordionItem;
</script>

<style scoped>
/* Animation keyframes for accordion */
@keyframes accordion-down {
  from {
    height: 0;
  }
  to {
    height: var(--radix-accordion-content-height);
  }
}

@keyframes accordion-up {
  from {
    height: var(--radix-accordion-content-height);
  }
  to {
    height: 0;
  }
}

.animate-accordion-down {
  animation: accordion-down 0.2s ease-out;
}

.animate-accordion-up {
  animation: accordion-up 0.2s ease-out;
}
</style>

// packages/design-system/registry/components/accordion/accordion.tsx
/**
 * Accordion Component - Collapsible Content Sections
 * CLAUDE.md Compliant: Professional sizing and spacing
 * WCAG AAA: Full keyboard navigation, ARIA support, and screen reader compatibility
 * CVA: Class Variance Authority for consistent styling
 * Universal Tokens: Uses design system tokens for consistency
 */

import React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { ChevronDownIcon } from '@heroicons/react/24/outline';
import { cn } from '../../lib/utils';

const accordionVariants = cva(
  [
    'border border-border rounded-lg',
    'bg-card text-card-foreground',
    'transition-all duration-200 ease-in-out'
  ],
  {
    variants: {
      variant: {
        default: 'shadow-sm hover:shadow-md',
        elevated: 'shadow-md hover:shadow-lg',
        outline: 'shadow-none',
        ghost: 'border-transparent shadow-none',
        // NSM Security Classification variants
        nsmOpen: 'border-l-4 border-l-green-600 shadow-sm',
        nsmRestricted: 'border-l-4 border-l-yellow-600 shadow-sm',
        nsmConfidential: 'border-l-4 border-l-red-600 shadow-sm',
        nsmSecret: 'border-l-4 border-l-gray-800 shadow-sm'
      },
      size: {
        sm: 'text-sm',
        md: 'text-base',
        lg: 'text-lg'
      },
      collapsible: {
        single: '',
        multiple: ''
      }
    },
    defaultVariants: {
      variant: 'default',
      size: 'md',
      collapsible: 'single'
    }
  }
);

const accordionItemVariants = cva(
  [
    'border-b border-border last:border-b-0',
    'transition-colors duration-200'
  ],
  {
    variants: {
      disabled: {
        true: 'opacity-50 cursor-not-allowed',
        false: ''
      }
    },
    defaultVariants: {
      disabled: false
    }
  }
);

const accordionTriggerVariants = cva(
  [
    'flex w-full items-center justify-between',
    'px-6 py-4 text-left font-medium',
    'transition-all duration-200 ease-in-out',
    'focus:outline-none focus:ring-2 focus:ring-primary/20 focus:ring-offset-2',
    'hover:bg-accent/5 active:bg-accent/10',
    'disabled:cursor-not-allowed disabled:opacity-50',
    // Professional minimum height
    'min-h-[3rem]'
  ],
  {
    variants: {
      size: {
        sm: 'px-4 py-3 text-sm min-h-[2.5rem]',
        md: 'px-6 py-4 text-base min-h-[3rem]',
        lg: 'px-8 py-5 text-lg min-h-[3.5rem]'
      }
    },
    defaultVariants: {
      size: 'md'
    }
  }
);

const accordionContentVariants = cva(
  [
    'overflow-hidden transition-all duration-200 ease-in-out',
    'data-[state=closed]:animate-accordion-up',
    'data-[state=open]:animate-accordion-down'
  ]
);

const accordionContentInnerVariants = cva(
  [
    'pb-4 pt-0'
  ],
  {
    variants: {
      size: {
        sm: 'px-4 pb-3',
        md: 'px-6 pb-4', 
        lg: 'px-8 pb-5'
      }
    },
    defaultVariants: {
      size: 'md'
    }
  }
);

// Types
export interface AccordionProps extends 
  Omit<React.HTMLAttributes<HTMLDivElement>, 'type'>,
  VariantProps<typeof accordionVariants> {
  readonly type?: 'single' | 'multiple';
  readonly value?: string | string[];
  readonly defaultValue?: string | string[];
  readonly onValueChange?: (value: string | string[]) => void;
  readonly disabled?: boolean;
  readonly nsmClassification?: 'OPEN' | 'RESTRICTED' | 'CONFIDENTIAL' | 'SECRET';
}

export interface AccordionItemProps extends 
  React.HTMLAttributes<HTMLDivElement>,
  VariantProps<typeof accordionItemVariants> {
  readonly value: string;
  readonly disabled?: boolean;
}

export interface AccordionTriggerProps extends 
  React.ButtonHTMLAttributes<HTMLButtonElement>,
  VariantProps<typeof accordionTriggerVariants> {
  readonly hideChevron?: boolean;
  readonly customIcon?: React.ReactNode;
}

export interface AccordionContentProps extends 
  React.HTMLAttributes<HTMLDivElement>,
  VariantProps<typeof accordionContentVariants> {
  readonly forceMount?: boolean;
}

// Context for managing accordion state
interface AccordionContextType {
  type: 'single' | 'multiple';
  value: string | string[];
  onItemToggle: (value: string) => void;
  disabled?: boolean;
  size?: 'sm' | 'md' | 'lg';
}

const AccordionContext = React.createContext<AccordionContextType | null>(null);

// Hook to use accordion context
function useAccordionContext(): AccordionContextType {
  const context = React.useContext(AccordionContext);
  if (!context) {
    throw new Error('Accordion components must be used within an Accordion');
  }
  return context;
}

// Context for individual accordion items
interface AccordionItemContextType {
  value: string;
  isOpen: boolean;
  disabled?: boolean;
  onToggle: () => void;
}

const AccordionItemContext = React.createContext<AccordionItemContextType | null>(null);

function useAccordionItemContext(): AccordionItemContextType {
  const context = React.useContext(AccordionItemContext);
  if (!context) {
    throw new Error('AccordionTrigger and AccordionContent must be used within an AccordionItem');
  }
  return context;
}

// Main Accordion Component
export const Accordion = React.forwardRef<HTMLDivElement, AccordionProps>(
  ({ 
    className, 
    variant, 
    size, 
    type = 'single',
    value: controlledValue,
    defaultValue,
    onValueChange,
    disabled = false,
    nsmClassification,
    children,
    ...props 
  }, ref) => {
    // State management for uncontrolled accordion
    const [uncontrolledValue, setUncontrolledValue] = React.useState<string | string[]>(
      defaultValue || (type === 'multiple' ? [] : '')
    );
    
    const isControlled = controlledValue !== undefined;
    const value = isControlled ? controlledValue : uncontrolledValue;
    
    // Auto-select NSM variant if classification is provided
    const finalVariant = nsmClassification 
      ? `nsm${nsmClassification.charAt(0).toUpperCase() + nsmClassification.slice(1).toLowerCase()}` as 'nsmOpen' | 'nsmRestricted' | 'nsmConfidential' | 'nsmSecret'
      : variant;

    const handleItemToggle = React.useCallback((itemValue: string) => {
      if (disabled) return;
      
      let newValue: string | string[];
      
      if (type === 'multiple') {
        const currentArray = Array.isArray(value) ? value : [];
        newValue = currentArray.includes(itemValue)
          ? currentArray.filter(v => v !== itemValue)
          : [...currentArray, itemValue];
      } else {
        newValue = value === itemValue ? '' : itemValue;
      }
      
      if (!isControlled) {
        setUncontrolledValue(newValue);
      }
      
      onValueChange?.(newValue);
    }, [disabled, type, value, isControlled, onValueChange]);

    const contextValue: AccordionContextType = {
      type,
      value,
      onItemToggle: handleItemToggle,
      disabled,
      size
    };

    return (
      <AccordionContext.Provider value={contextValue}>
        <div
          ref={ref}
          className={cn(accordionVariants({ variant: finalVariant, size }), className)}
          data-orientation="vertical"
          {...props}
        >
          {/* NSM Classification for screen readers */}
          {nsmClassification && (
            <span className="sr-only">
              NSM Classification: {nsmClassification}
            </span>
          )}
          {children}
        </div>
      </AccordionContext.Provider>
    );
  }
);

Accordion.displayName = 'Accordion';

// Accordion Item Component
export const AccordionItem = React.forwardRef<HTMLDivElement, AccordionItemProps>(
  ({ 
    className, 
    value: itemValue, 
    disabled: itemDisabled = false, 
    children, 
    ...props 
  }, ref) => {
    const { value, onItemToggle, disabled: accordionDisabled, type } = useAccordionContext();
    
    const isDisabled = accordionDisabled || itemDisabled;
    const isOpen = type === 'multiple' 
      ? Array.isArray(value) && value.includes(itemValue)
      : value === itemValue;

    const handleToggle = React.useCallback(() => {
      if (!isDisabled) {
        onItemToggle(itemValue);
      }
    }, [isDisabled, onItemToggle, itemValue]);

    const itemContextValue: AccordionItemContextType = {
      value: itemValue,
      isOpen,
      disabled: isDisabled,
      onToggle: handleToggle
    };

    return (
      <AccordionItemContext.Provider value={itemContextValue}>
        <div
          ref={ref}
          className={cn(accordionItemVariants({ disabled: isDisabled }), className)}
          data-state={isOpen ? 'open' : 'closed'}
          data-disabled={isDisabled || undefined}
          {...props}
        >
          {children}
        </div>
      </AccordionItemContext.Provider>
    );
  }
);

AccordionItem.displayName = 'AccordionItem';

// Accordion Trigger Component
export const AccordionTrigger = React.forwardRef<HTMLButtonElement, AccordionTriggerProps>(
  ({ 
    className, 
    size, 
    hideChevron = false, 
    customIcon,
    children, 
    ...props 
  }, ref) => {
    const { size: accordionSize } = useAccordionContext();
    const { isOpen, disabled, onToggle, value } = useAccordionItemContext();
    
    const finalSize = size || accordionSize;

    return (
      <button
        ref={ref}
        type="button"
        className={cn(accordionTriggerVariants({ size: finalSize }), className)}
        disabled={disabled}
        aria-expanded={isOpen}
        aria-controls={`accordion-content-${value}`}
        data-state={isOpen ? 'open' : 'closed'}
        onClick={onToggle}
        {...props}
      >
        <span className="text-left">{children}</span>
        
        {!hideChevron && (
          <span 
            className={cn(
              'ml-2 flex-shrink-0 transition-transform duration-200',
              isOpen && 'rotate-180'
            )}
            aria-hidden="true"
          >
            {customIcon || (
              <ChevronDownIcon className="h-5 w-5" />
            )}
          </span>
        )}
      </button>
    );
  }
);

AccordionTrigger.displayName = 'AccordionTrigger';

// Accordion Content Component
export const AccordionContent = React.forwardRef<HTMLDivElement, AccordionContentProps>(
  ({ className, size, children, forceMount = false, ...props }, ref) => {
    const { size: accordionSize } = useAccordionContext();
    const { isOpen, value } = useAccordionItemContext();
    
    const finalSize = size || accordionSize;

    if (!forceMount && !isOpen) {
      return null;
    }

    return (
      <div
        ref={ref}
        className={cn(accordionContentVariants(), className)}
        id={`accordion-content-${value}`}
        role="region"
        aria-labelledby={`accordion-trigger-${value}`}
        data-state={isOpen ? 'open' : 'closed'}
        style={{
          '--accordion-content-height': 'var(--radix-accordion-content-height)',
          '--accordion-content-width': 'var(--radix-accordion-content-width)',
        } as React.CSSProperties}
        {...props}
      >
        <div className={cn(accordionContentInnerVariants({ size: finalSize }))}>
          {children}
        </div>
      </div>
    );
  }
);

AccordionContent.displayName = 'AccordionContent';

// Export variants and types
export { accordionVariants, accordionItemVariants, accordionTriggerVariants, accordionContentVariants };
export type { VariantProps };
